import { resolveColorName } from './color-crosswalk.mjs'

export function emitBrandTokensCss({ colors, fonts, meta = {} }) {
  const { potxHash = '(unknown)', date = '(unknown)' } = meta
  const lines = []

  lines.push('/* GENERATED by scripts/extract-brand.mjs — do not edit by hand. */')
  lines.push(`/* POTX hash: ${potxHash}  |  extracted: ${date} */`)
  lines.push('')
  lines.push(':root {')

  for (const hex of colors) {
    const name = resolveColorName(hex)
    lines.push(`  --${name}: #${hex.toUpperCase()};`)
  }

  lines.push('')
  lines.push(`  --sap-font-major: '${fonts.major}', 'Helvetica Neue', Arial, sans-serif;`)
  lines.push(`  --sap-font-minor: '${fonts.minor}', 'Helvetica Neue', Arial, sans-serif;`)

  lines.push('')
  lines.push('  --sap-radius-card: 0.5rem;')
  lines.push('  --sap-radius-button: 0.25rem;')
  lines.push('  --sap-shadow-card: 0 1px 4px rgba(0, 0, 0, 0.08);')

  lines.push('}')
  lines.push('')
  return lines.join('\n')
}
